FROM node:10-alpine as builder

ENV WORKDIR /home/app
WORKDIR $WORKDIR

RUN apk update && apk add git yarn

COPY package.json .
COPY yarn.lock .

RUN yarn install --network-timeout 1000000

COPY . .

ARG VUE_APP_ROOT_API
ARG KEYCLOAK_ISSUER
ARG KEYCLOAK_AUTHORIZATION_ENDPOINT
ARG KEYCLOAK_USERINFO_ENDPOINT
ARG KEYCLOAK_END_SESSION_ENDPOINT
ARG KEYCLOAK_JWKS_URI
ARG KEYCLOAK_TOKEN_ENDPOINT
ARG KEYCLOAK_CHECK_SESSION_IFRAME
ARG KEYCLOAK_CLIENT_ID
ARG VUE_APP_HOTJAR_PROJECT_KEY
ARG VUE_APP_SENTRY_DSN_ENDPOINT
ARG VUE_APP_HELPHERO

ENV VUE_APP_ROOT_API "${VUE_APP_ROOT_API}"
ENV KEYCLOAK_ISSUER "${KEYCLOAK_ISSUER}"
ENV KEYCLOAK_AUTHORIZATION_ENDPOINT "${KEYCLOAK_AUTHORIZATION_ENDPOINT}"
ENV KEYCLOAK_USERINFO_ENDPOINT "${KEYCLOAK_USERINFO_ENDPOINT}"
ENV KEYCLOAK_END_SESSION_ENDPOINT "${KEYCLOAK_END_SESSION_ENDPOINT}"
ENV KEYCLOAK_JWKS_URI "${KEYCLOAK_JWKS_URI}"
ENV KEYCLOAK_TOKEN_ENDPOINT "${KEYCLOAK_TOKEN_ENDPOINT}"
ENV KEYCLOAK_CHECK_SESSION_IFRAME "${KEYCLOAK_CHECK_SESSION_IFRAME}"
ENV KEYCLOAK_CLIENT_ID "${KEYCLOAK_CLIENT_ID}"
ENV VUE_APP_HOTJAR_PROJECT_KEY "${VUE_APP_HOTJAR_PROJECT_KEY}"
ENV VUE_APP_SENTRY_DSN_ENDPOINT "${VUE_APP_SENTRY_DSN_ENDPOINT}"
ENV VUE_APP_HELPHERO "${VUE_APP_HELPHERO}"

RUN yarn build

FROM nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /home/app/dist /usr/share/nginx/html/connect
