FROM debian:latest

# Set up repo for ffmpeg using repo from official install docs
# https://github.com/ccrisan/motioneye/wiki/Install-On-Ubuntu
#RUN apt-get -y install software-properties-common && \
    #add-apt-repository -y ppa:kirillshkrogalev/ffmpeg-next && \
    #apt-get -y update && \
    #apt-get clean
RUN echo "deb http://www.deb-multimedia.org jessie main non-free" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get -y --allow-unauthenticated install deb-multimedia-keyring curl lsb-release

RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
	echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee /etc/apt/sources.list.d/google-cloud-sdk.list && \
	curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
	apt-get update

RUN apt-get -y install \
    ffmpeg \
	google-cloud-sdk \
    git \
    libcurl4-openssl-dev \
    libjpeg-dev \
    libssl-dev \
    motion \
    python-dev \
    python-pip \
    v4l-utils \
    wget && \
    apt-get clean

ENV CLOUDSDK_PYTHON_SITEPACKAGES=1

# These are used for gcloud and gsutil. If not set, gsutil will not function.
ENV GCLOUD_SVC_ACCOUNT ""
ENV GCLOUD_SVC_KEY ""
ENV GCLOUD_BUCKET ""

# Install motioneye itself
RUN pip install motioneye

# These should be near the end for easy tweaking
ADD ./bootstrap.sh /bootstrap.sh
ADD ./gcloud-rsync.sh /usr/local/bin/gcloud-rsync.sh

# Create media config dirs. These need to be persistent to save configuration 
# and images/videos generated by motion processes.
RUN mkdir -p /etc/motioneye /var/lib/motioneye && chmod o+rw /etc/motioneye /var/lib/motioneye
VOLUME [ "/etc/motioneye", "/var/lib/motioneye" ]
EXPOSE 8765
CMD /bootstrap.sh
