FROM node:alpine AS base

RUN apk update
RUN apk upgrade
RUN apk add bash g++ make python3 git

ARG GIT_VERSION=0
LABEL vcs-ref=$GIT_VERSION
ENV _GIT_VERSION=$GIT_VERSION

ARG GIT_IT=0
ENV _GIT_IT=$GIT_IT

WORKDIR /usr/src/wallet-ui

COPY package*.json ./

RUN npm install

ARG HERMEZ_API_URL
ARG BATCH_EXPLORER_URL
ARG HERMEZ_CONTRACT_ADDRESS
ARG WITHDRAWAL_DELAYER_CONTRACT_ADDRESS

ENV REACT_APP_HERMEZ_API_URL ${HERMEZ_API_URL}
ENV REACT_APP_BATCH_EXPLORER_URL ${BATCH_EXPLORER_URL}
ENV REACT_APP_HERMEZ_CONTRACT_ADDRESS ${HERMEZ_CONTRACT_ADDRESS}
ENV REACT_APP_WITHDRAWAL_DELAYER_CONTRACT_ADDRESS ${WITHDRAWAL_DELAYER_CONTRACT_ADDRESS}

COPY . .

RUN npm run build

EXPOSE 80

CMD ["npm", "run", "start:prod"]
