FROM hipache:0.3.1
MAINTAINER fernando@tutum.co

ENV SERVER_ACCESSLOG /var/log/hipache-access.log
ENV SERVER_WORKERS 10
ENV SERVER_MAXSOCKETS 100
ENV SERVER_DEADBACKENDTTL 30
ENV SERVER_TCPTIMEOUT 30
ENV SERVER_RETRYONERROR 3
ENV SERVER_DEADBACKENDON500 false
ENV SERVER_HTTPKEEPALIVE false
ENV SERVER_LRUCACHE_SIZE 5
ENV SERVER_LRUCACHE_TTL 5
ENV SERVER_PORT 80
ENV SERVER_ADDRESS 0.0.0.0
ENV DRIVER redis:

ADD . /
RUN chmod +x /*.sh

EXPOSE 80
CMD ["/run.sh"]