# Get Linux
FROM nvidia/cuda:11.2.2-cudnn8-runtime-ubuntu20.04

# Polus platform file extension
ENV POLUS_EXT=".ome.tif"

# Container log level
ENV POLUS_LOG="INFO"

# Data and code directories
ENV EXEC_DIR="/opt/executables"
ENV DATA_DIR="/data"

RUN mkdir ${EXEC_DIR} && \
    mkdir ${DATA_DIR}}

# Instal Python
RUN apt update && \
    apt install software-properties-common -y && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt install python3.9 python3.9-dev python3.9-distutils curl openjdk-8-jre build-essential -y && \
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python3.9 get-pip.py && \
    apt autoremove -y && \
    rm -rf /var/lib/apt/lists/*

COPY VERSION ${EXEC_DIR}
COPY src ${EXEC_DIR}/

RUN ln -sf /usr/bin/python3.9 /usr/bin/python3

RUN pip3 install -r ${EXEC_DIR}/requirements.txt --no-cache-dir

# Install requirements
RUN pip3 install bfio[all]==2.1.9 --no-dependencies
RUN pip3 install tifffile==2020.11.18
WORKDIR ${EXEC_DIR}

# Set the log level to hide some basic warning/info generated by Tensorflow
#ENV TF_CPP_MIN_LOG_LEVEL=2

# Fix for cudnn error on RTX gpus
ENV TF_FORCE_GPU_ALLOW_GROWTH=true


RUN python3 -c "import deepcell;from deepcell.applications import Mesmer; app = Mesmer()"


# Default command. Additional arguments are provided through the command line
ENTRYPOINT ["python3", "main.py"]
