# DOCKER-VERSION        1.3.2

FROM iojs:onbuild
MAINTAINER Ryan Low, ryan_low_123@hotmail.com

ENV HUBOT_PORT 8080
ENV HUBOT_ADAPTER slack
ENV HUBOT_NAME cortana
ENV HUBOT_GOOGLE_API_KEY xxxxxxxxxxxxxxxxxxxxxx
ENV HUBOT_SLACK_TOKEN xoxb-9260529638-W4UUDNiS8CP6Pxm1MqV6N3cP
ENV HUBOT_SLACK_TEAM rebelone
ENV HUBOT_SLACK_BOTNAME ${HUBOT_NAME}
ENV PORT ${HUBOT_PORT}

EXPOSE ${HUBOT_PORT}

CMD bin/hubot
